version: '3.7'

services:
  galera_health_check:
    container_name: galera_health_check
    image: ghcr.io/seaweedbraincy/galera_cluster_healthcheck:latest
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
       DB_USER: <REPLACE_ME> # required
       DB_PASSWORD: <REPLACE_ME> # required
       DB_HOST: <REPLACE_ME> # required
       DB_PORT: 3306 # optional. Default is 3306
       CHECK_INTERVAL: 60 # optional. Default is 60. Healthcheck interval in seconds
       ALERT_THROTTLE: 10800 # optional. Default is 10800s (3h). Amount of time in senconds between 2 consecutive alerts
       NODE_NAME: <REPLACE_ME> # required. Used to identify the node in the alert message
       CLUSTER_MIN_SIZE: <REPLACE_ME> # required. Minimum number of nodes in the cluster, used to determine if the cluster is in a degraded state
       WEBHOOK_URL: <REPLACE_ME> # required. Discord webhook URL for notifications
    volumes:
      - ./docker_logs:/app/logs 
    restart: always
